### PR TITLE
Fix for 'No iOS devices connected.' 

### LINKED ISSUE #1404: react-native run-ios --device not working with XCode 12.5 CLI tools
## Environment

```
System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 626.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /var/folders/34/_v0h6lqn0x17yx6pppvqrnbmcjbc20/T/yarn--1619714124765-0.3284344217580091/node
    Yarn: 1.22.10 - /var/folders/34/_v0h6lqn0x17yx6pppvqrnbmcjbc20/T/yarn--1619714124765-0.3284344217580091/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

After upgrading to the latest version of Xcode (12.5), I can no longer run my react-native project on a physical device. Running `react-native run-ios --device=X` always results in an error and a message that there are no available devices to run on:

image

I've tracked the issue down to [this line](https://github.com/react-native-community/cli/blob/641b21f583c97e3d48ce87d5fe804f42db92fa5c/packages/platform-ios/src/commands/runIOS/index.ts#L91). It seems that `xcrun xctrace list devices` no longer outputs to stderr:

image

`tail error` => empty, `tail out` => list of devices. Changing the above line to `stdout` instead of `stderr` fixes the issue locally for me.

## Reproducible Demo

This _should_ be reproducible on any react-native project when running XCode 12.5, but if I'm mistaken, let me know and I'll try to put together a minimal demo.

### PR DESCRIPTION
**Pull request by thang2162**
Fixes #1404

Summary:
---------

Fix for 'No iOS devices connected.' error when using 'run-ios --device' on XCode 12.5 with backwards compatibility. Checks output using stderr and uses stdout when blank text is returned.

Test Plan:
----------

### CODE REVIEW

**Review by thymikee — APPROVED** [review]
👌🏼

File: packages/platform-ios/src/commands/runIOS/index.ts [hunk 1]
```diff
@@ -87,8 +87,10 @@ function runIOS(_: Array<string>, ctx: Config, args: FlagsT) {
 
   let devices;
   try {
+    const out = execa.sync('xcrun', ['xctrace', 'list', 'devices']);
     devices = parseXctraceIOSDevicesList(
-      execa.sync('xcrun', ['xctrace', 'list', 'devices']).stderr,
+    // Xcode 12.5 introduced a change to output the list to stdout instead of stderr
+      out.stderr === "" ? out.stdout : out.stderr,
```
Comment (thymikee) [inline packages/platform-ios/src/commands/runIOS/index.ts:93]:
```suggestion
      // Xcode 12.5 introduced a change to output the list to stdout instead of stderr
      out.stderr === "" ? out.stdout : out.stderr,
```

**Comment by thymikee** [comment]
Linter is not happy. Can you run `npx lint --fix`?

**Comment by brodybits** [comment]
Will this fix be published soon?

**Comment by thang2162** [comment]
Should already be rolled out. It’s at least working with npx.

**Comment by thymikee** [comment]
It's not yet released. I asked @grabbou to do so.

**Comment by redefinered** [comment]
is this fix released?

**Comment by thymikee** [comment]
@redefinered yes, it's included in v6.0.0-rc.0 and v5.0.1.
