### PR TITLE
fix: delete `com.` prefix in package name

### LINKED ISSUE #1903: --package-name option doesn't work properly
## Environment

System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.83 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/yaroslav/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

If the --package-name value provided does not start with `com.`, the tool automatically adds `com.` to the beginning of the package name value. For instance, running the command:
 `npx @react-native-community/cli init ProjectName --package-name net.company.projectname` 
 would result in a package name of `com.net.company.projectname`. This issue can cause confusion and may require users to manually modify their package names after initialization. Package names are not required to start with `com`.,

## Reproducible Demo

Run the following command and check the result:
```
npx @react-native-community/cli init ProjectName --package-name net.company.projectname
```

### PR DESCRIPTION
**Pull request by szymonrybczak**
Summary:
---------
This PR removes the addition of `com.` to the package name during project initialization.
Closes #1903

Test Plan:
----------

1. Clone the repository and do all the required steps from the [Contributing guide](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md)
2. Run this command:

```other
node /path/to/react-native-cli/packages/cli/build/bin.js init ProjectName --package-name net.company.projectname
```
3. Check two things: 

- `net.company.projectname` should be used as package name, without `com.` prefix
-  path `android/app/src/debug/java/net/company/projectname` should exsist.

### CODE REVIEW

**Comment by TMisiukiewicz** [comment]
I think we can totally remove `getPackageNameDetails` and just use the `cleanPackageName` value. We probably don't need all the rest of the values from this function anymore.

We also need to adjust `createAndroidPackagePaths` function because since we are operating on a template where we have `android/app/src/main/java/com/app`, right now it generates `android/app/src/main/java/com/net/company/projectname` 🤔

**Review by cortinico — APPROVED** [review]

File: packages/cli/src/commands/init/editTemplate.ts [hunk 1]
```diff
@@ -101,49 +101,33 @@ async function processDotfiles(filePath: string) {
   await renameFile(filePath, `_${dotfile}`, `.${dotfile}`);
 }
 
-function getPackageNameDetails(packageName: string) {
-  const cleanPackageName = packageName.replace(/[^\p{L}\p{N}.]+/gu, '');
```
Comment (TMisiukiewicz) [inline packages/cli/src/commands/init/editTemplate.ts:105]: i think we should still sanitize package name with this regex, to prevent failing to process the template when someone type e.g. `--package-name "c[om.package.name"

**Comment by TMisiukiewicz** [comment]
Just one small comment, except from that it works fine 👏

**Review by adamTrz — APPROVED** [review]
