### PR TITLE
fix: throw a better error when configuration is invalid

### LINKED ISSUE #1181: Unrecognized command error is thrown when configuration in `react-native.config.js` is invalid.
## Environment

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 1.96 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /var/folders/2w/n4f1z31n5hq0y80gx43nzkc40000gn/T/yarn--1590687625507-0.40631584938188037/node
    Yarn: 1.22.4 - /var/folders/2w/n4f1z31n5hq0y80gx43nzkc40000gn/T/yarn--1590687625507-0.40631584938188037/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

When using React Native CLI with invalid config provided in `react-native.config.js` file, `Unrecognized command` error is thrown, no matter which command is invoked.

## Reproducible Demo
Freshly initialised React Native project with any config that is invalid ie.:
```js
// @flow

module.exports = {
  project: {
    android: {
      wrongConfiguration: 'test',
    },
  },
  dependencies: {
    'react-native-amplitude-analytics': {
      platforms: {
        android: null,
      },
    },
    'react-native-text-size': {
      platforms: {
        ios: null,
      },
    },
  },
};

```

## Additional notes

Using verbose flag prints the actual issue description, although the final error remains as "Unknown command".

```bash
$ ~/Projects/react-native/TestConfig/node_modules/.bin/react-native info --verbose
debug Unknown option project.android.wrongConfiguration with value ""test"" was found. This is either a typing error or a user mistake. Fixing it will remove this message.
debug Failed to load configuration of your project. Only a subset of commands will be available.
error Unrecognized command "info".
```

### PR DESCRIPTION
**Pull request by dratwas**
Summary:
---------

Fixes #1181 

Throw an error with the correct message when configuration fails to load because of an invalid shape. Before the error was lost and running commands resulted in "Unrecognized command" error. The details were only available with `--verbose` flag and resulted in quite a confusion and poor experience.

Before:
image

After:
Screen Shot 2020-05-28 at 22 48 05

Test Plan:
- 

Use the below invalid config:
```js
module.exports = {
  project: {
    android: {
      wrongConfiguration: 'test',
    },
  },
};
```
- run `react-native config` or any other command requiring config
- The correct error should be shown

### CODE REVIEW

File: packages/cli/src/index.ts [hunk 1]
```diff
@@ -222,10 +222,7 @@ async function setupAndRun() {
     }
   } catch (e) {
     logger.enable();
```
Comment (thymikee) [inline packages/cli/src/index.ts:224]: we can remove this now as well

File: packages/tools/src/errors.ts [hunk 2]
```diff
@@ -9,8 +9,7 @@ export class CLIError extends Error {
       this.stack =
         typeof originalError === 'string'
           ? originalError
-          : originalError.stack ||
-            ''
```
Comment (thymikee) [inline packages/tools/src/errors.ts:13]: clearly a regression

File: packages/cli/src/tools/config/errors.ts [hunk 3]
```diff
@@ -31,5 +31,9 @@ export class JoiError extends CLIError {
         })
         .join(),
     );
+
+    if (Error.captureStackTrace) {
+      Error.captureStackTrace(this, JoiError);
+    }
```
Comment (thymikee) [inline packages/cli/src/tools/config/errors.ts:37]: Getting rid of internal stack, pointing to a place where the error was thrown

image

**Comment by thymikee** [comment]
@grabbou this is your field, pls review :)
