### PR TITLE
fix: template name replacement in package.json

### LINKED ISSUE #1456: Template's `placeholderName` is not replaced everywhere.
## Environment
```
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 222.09 MB / 16.00 GB
    Shell: 5.8 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
## Description

When using `init` command with `--template` option, template's `placeholderName` is not being replaced in `package.json`'s scripts section.

## Reproducible Demo

I've tried different placeholderName forms:
e.g `template/package.json` scripts:
```
"ios:dev": "react-native run-ios --scheme HelloWorldDevelopment",
"ios:dev": "react-native run-ios --scheme \"HelloWorld-Development\"",
"ios:dev": "react-native run-ios --scheme \"HelloWorldDevelopment\"",
```
e.g `template.config.js`:
```
module.exports = {
  placeholderName: "HelloWorld",
  titlePlaceholder: "Hello App Display Name",
  templateDir: "./template",
};
```
```sh
react native init MyTemplateTest --template my-template
```
The resulting `package.json` scripts: 
```
"ios:dev": "react-native run-ios --scheme HelloWorldDevelopment",
"ios:dev": "react-native run-ios --scheme \"HelloWorld-Development\"",
"ios:dev": "react-native run-ios --scheme \"HelloWorldDevelopment\"",
```
Same as in template, while I expect `HelloWorld` to be replaced with provided project name e.g. `MyTemplateTest`

### PR DESCRIPTION
**Pull request by Esemesek**
Summary:
---------

Fixes #1456

Seems like our special treatment of `package.json` during `init` caused not everything to be replaced correctly. With this fix everything will be replaced correctly except the `name` won't be converted to lowercase `npmjs` package naming.

Test Plan:
----------

Added test case assertions for this one in the `editTemplate.test.ts`.

### CODE REVIEW

**Comment by Esemesek** [comment]
@thymikee @grabbou What do you think about parsing `package.json` additionally to convert the `name` keyword to be lowercased?

File: packages/cli/src/commands/init/editTemplate.ts [hunk 1]
```diff
@@ -34,14 +33,6 @@ function replaceNameInUTF8File(
   if (fileContent !== replacedFileContent) {
     fs.writeFileSync(filePath, replacedFileContent, 'utf8');
   }
-
-  if (isPackageJson) {
-    fs.writeFileSync(
-      filePath,
-      fileContent.replace(templateName, projectName.toLowerCase()),
```
Comment (grabbou) [inline packages/cli/src/commands/init/editTemplate.ts:41]: I think better would be to replace `fileContent` with `replacedFileContent`. That way, we maintain `lowerCase` behaviour, at the same time, we do not overwrite changes (that happened, if any) when working with `package.json` .

**Review by grabbou — CHANGES_REQUESTED** [review]
