### PR TITLE
fix: give a better error message when CocoaPods linking fails

### LINKED ISSUE #273: react-native link @react-native-community/async-storage fails
## Environment

```
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 352.69 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.8.5 
      react-native: ^0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

```

## Description

The link in this new lib fails. The commands states to to log a bug:

```
$ react-native link @react-native-community/async-storage
info Linking "@react-native-community/async-storage" iOS dependency
error Something went wrong while linking. Error: Cannot read property 'match' of undefined 
Please file an issue here: https://github.com/react-native-community/react-native-cli/issues
error Cannot read property 'match' of undefined
```

## Reproducible Demo

`react-native link @react-native-community/async-storage`

### PR DESCRIPTION
**Pull request by grabbou**
Summary:
---------

Right now, when Podfile doesn't have a market text or the target name is different, link fails with a cryptic message. This adds an explicit error message.

Fixes #273 

Test Plan:
----------

Use a Podfile w/o market text and change the name of the target. See the error happen.

### CODE REVIEW

**Comment by grabbou** [comment]
Note: CocoaPods errors are expected and to be fixed.

File: packages/platform-ios/src/link-pods/findMarkedLinesInPodfile.js [hunk 1]
```diff
@@ -7,7 +7,7 @@
  * @format
  */
 
-const MARKER_TEXT = '# Add new pods below this line';
+export const MARKER_TEXT = '# Add new pods below this line';
```
Comment (thymikee) [inline packages/platform-ios/src/link-pods/findMarkedLinesInPodfile.js]: can we improve this text to include `DO NOT REMOVE`? I had no idea it's a marker for CLI

**Comment by grabbou** [comment]
So we need a legacy marker and a new marker for now. Sounds fine to me, we
need to document this too (even tho it's getting deprecated). Let's make it
a ticket.

File: packages/platform-ios/src/link-pods/findMarkedLinesInPodfile.js (hunk 1 above)
Comment (grabbou) [reply packages/platform-ios/src/link-pods/findMarkedLinesInPodfile.js]: Yes, but we need to handle both this and legacy one. Let's do that in a sep. ticket + some documentation on how this is set up.

File: packages/platform-ios/src/link-pods/registerNativeModule.js [hunk 2]
```diff
@@ -31,5 +35,21 @@ function getLinesToAddEntry(podLines, {projectName}) {
     return linesToAddPodWithMarker;
   }
   const firstTargetLined = findPodTargetLine(podLines, projectName);
+  if (firstTargetLined === null) {
+    throw new CLIError(
+      inlineString(`
+        We couldn't find a target to add a CocoaPods dependency.
+        
+        Make sure that you have a ${chalk.dim(
```
Comment (thymikee) [inline packages/platform-ios/src/link-pods/registerNativeModule.js]: can we add `"` quotes around the dimmed lines so they're easier distinguishable for users with poor colors?

**Comment by grabbou** [comment]
Opened up an issue in the meantime: https://github.com/react-native-community/cli/issues/322

File: packages/platform-ios/src/link-pods/registerNativeModule.js (hunk 2 above)
Comment (grabbou) [reply packages/platform-ios/src/link-pods/registerNativeModule.js]: Done! Good idea.

**Comment by grabbou** [comment]
@thymikee feel free to rebase your one for fixed CocoaPods test.
