### PR TITLE
fix: Replace calling internal React Native scripts for launching Metro with CLI's script

### LINKED ISSUE #1799: Is running packager by calling react-native internal script still necessary for run-android?
# Background

I'm actively working on preparing a react-native monorepo template with enabled hoisting.
I've everything working besides one thing. 
When I'm running `react-native run-android` packager is starting from monorepo root(`./`) instead of app package `./apps/app`
I can workaround it by running packager upfront but I would love to have that template working without such workarounds.

# Findings

I've dived deeply into how I can work around it and figured out that there is no option to solve that without patching `react-native`.

### Current flow

Currently running packager for `run-android` is working the following way:

- CLI is calling [startServerInNewWindow](https://github.dev/react-native-community/cli/blob/f308a560ef8b771542578d876866c0e25920ff72/packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts#L1)
- `startServerInNewWindow` 
  - is overriding `.packager.env`
  - and is calling [lauchPackager.sh](https://github.dev/facebook/react-native/blob/4f94577d4281f76e25b2874158274c940d6eb3b5/scripts/launchPackager.command#L1)
- `lauchPackager.sh` is calling [packager.sh](https://github.dev/facebook/react-native/blob/4f94577d4281f76e25b2874158274c940d6eb3b5/scripts/packager.sh)
- `packager.sh` is calling `react-native start` from `PROJECT_ROOT` which is statically set to the path relative to `node_modules/react-native`

### Why is that a problem?

1. Currently the simplest option to change `PROJECT_ROOT` from CLI perspective is to overwrite `PROJECT_ROOT` environment variable inside `.packager.env`
    - In the currently released react-native 0.71 `packager.sh` is always overwriting `PROJECT_ROOT` path with a path relative to the script location.
    - In future version(react-native master) there it accepts `PROJECT_ROOT` from outside.
    - Sadly there is still [this condition](https://github.dev/facebook/react-native/blob/4f94577d4281f76e25b2874158274c940d6eb3b5/scripts/packager.sh#L11) that will overwrite this path because in monorepo we have hoisting so the react-native package is located in monorepo root instead `PROJECT_ROOT`

2. Generally configuration of `react-native start` from `CLI` perspective is limited. 
It seems that `packager.sh` [accepts additional arguments (with `"$@"` at the end)](https://github.com/facebook/react-native/blob/2430d1fcf3b7eaaa7fe78912fb7644c0b558dec3/scripts/packager.sh#L24) that will be forwarded to `react-native start`.
However [`launchPackager.command`](https://github.com/facebook/react-native/blob/2430d1fcf3b7eaaa7fe78912fb7644c0b558dec3/scripts/launchPackager.command#L28-L30) is not forwarding it from `CLI`

## Question

1. I'm curious what is the story behind this solution where `CLI` have to call `react-native internal script` that will call `CLI`.
Maybe there is someone who has some background on this one?

2. Is this script treated internally in react-native as something that should be used by the community?
This question is based on [this comment](https://github.com/facebook/react-native/blob/2430d1fcf3b7eaaa7fe78912fb7644c0b558dec3/scripts/packager.sh#L17) inside `packager.sh` that sounds like it is something for internal react-native testing.

3. If this is something that should be used by the community then I'm wondering if there is a way to make it more configurable from a `CLI` perspective.

## Reproducible demo:

- clone repo https://github.com/MateWW/react-native-new-arch-monorepo
- install dependencies
- make sure you have packager running
- trigger `yarn android`(doesn't matter if you will do that from app directory or root)

### PR DESCRIPTION
**Pull request by szymonrybczak**
Summary:
---------
Closes #1799 

Replace calling internal React Native scripts for launching Metro with CLI's script.

Also this PR, changes the logic and right now it isn't starting packager from [relative path](https://github.com/facebook/react-native/blob/main/scripts/packager.sh#L11), but it launches packager from `config.root`.
CleanShot 2023-02-06 at 10 44 13@2x

Test Plan:
----------
1. `yarn react-native run-android` - should run correctly metro

### CODE REVIEW

File: packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts [hunk 1]
```diff
@@ -17,19 +18,19 @@ export function startServerInNewWindow(
     : 'launchPackager.command';
   const packagerEnvFilename = isWindows ? '.packager.bat' : '.packager.env';
   const portExportContent = isWindows
-    ? `set RCT_METRO_PORT=${port}`
-    : `export RCT_METRO_PORT=${port}`;
+    ? `set RCT_METRO_PORT=${port}\nset PROJECT_ROOT=${projectRoot}`
+    : `export RCT_METRO_PORT=${port}\nexport PROJECT_ROOT=${projectRoot}`;
```
Comment (MateWW) [inline packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:22]: I'm wondering if we still need those files. 
You have moved it out of the react-native context so I believe it's no longer used by any of the building scripts.
Maybe instead of doing it this strange way, we can pass those environment variables as an argument.

File: packages/cli-plugin-metro/launchPackager.bat [hunk 2]
```diff
@@ -0,0 +1,7 @@
+@echo off
```
Comment (MateWW) [inline packages/cli-plugin-metro/launchPackager.bat:1]: Do we still need those scripts?
I don't see any benefit in having those files separated.
Can we try to mimic those inside execa calls?
I see that at least `cwd` can be set without using it from `PROJECT_ROOT`

**Review by MateWW — COMMENTED** [review]
Thank you very much for opening this PR! 🚀🥳
It's something I cannot wait for!

File: packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts (hunk 1 above)
Comment (MateWW) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:22]: Due to `open` limitations we need this additional step.
Feel free to resolve this.

File: packages/cli-plugin-metro/launchPackager.bat (hunk 2 above)
Comment (MateWW) [reply packages/cli-plugin-metro/launchPackager.bat:1]: Due to `open` limitations we need this additional step.
Feel free to resolve this.

**Comment by MateWW** [comment]
Can we verify if moving `process.env` does not break anything inside react-native?
Are there any parts in react-native that are depending on it?

File: packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts [hunk 3]
```diff
@@ -6,8 +6,12 @@ import {logger} from '@react-native-community/cli-tools';
 export function startServerInNewWindow(
   port: number,
   terminal: string,
-  reactNativePath: string,
+  projectRoot: string,
 ) {
+  const reactNativeCliPath = path.dirname(
```
Comment (tido64) [inline packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: This is going to introduce all sorts of issues in monorepos. In the following example, can you guess which version of `@react-native-community/cli-plugin-metro` gets used?
```
root
├── node_modules
│   └── @react-native-community/cli-metro-plugin <-- which version got hoisted here?
├── package.json
└── packages
    ├── app-one
    │   ├── node_modules
    │   │   └── react-native@0.70
    │   ├── package.json
    │   └── src
    └── app-two
        ├── node_modules
        │   └── react-native@0.71
        ├── package.json
        └── src
```

Comment (tido64) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: It's also relying on hoisting. Not all package managers do this. If you're using pnpm, they transitive dependencies are only available for the package that depended on them. With this solution, the project is required to add `@react-native-community/cli-plugin-metro` in their own `package.json` for this to work. That's a breaking change, and it adds unnecessary burden on the app author.

Comment (szymonrybczak) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: But do we have any other options? Right now in monorepos when launching `npx react-native start` from e.g. `app-one` it will start packager from root of monorepo, so `app-one` won't bundle correctly. With this change only monorepos that contains apps with different RN version will have to add this pacakge `@react-native-community/cli-plugin-metro` to `package.json`.

Comment (tido64) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: > Right now in monorepos when launching `npx react-native start` from e.g. `app-one` it will start packager from root of monorepo, so `app-one` won't bundle correctly.

This sounds like a bug. Do we have a repro for this? `npx react-native start` should start with the `local node_modules/.bin` before retrying from parent directories. If you ran this command under `packages/app-one` and it has different version of `react-native` from the rest of the repository, `npx` should find `packages/app-one/node_modules/.bin/react-native`.

Comment (szymonrybczak) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: > Do we have a repro for this? 

Yeah, we have repro [here](https://github.com/MateWW/react-native-new-arch-monorepo/). When you launch `npx react-native run-ios` or `npx react-native run-android` inside `WorldHello` or `HelloWorld` metro bundler will launch from root of monorepo. I previously wrote about `npx react-native start`, but it's about `run-ios` and `run-android` my mistake, sorry 😅

Comment (tido64) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: I've had a quick look at how `run-android` launches the packager, and I agree with @cortinico. You should not call the [`launchPackager`](https://github.com/facebook/react-native/blob/main/scripts/launchPackager.command) (or the [underlying script](https://github.com/facebook/react-native/blob/main/scripts/packager.sh) it runs). They're both assuming that `react-native` is always installed within the project root. In a monorepo, this isn't always true.

The script ends up calling `"$REACT_NATIVE_ROOT/cli.js" start --custom-log-reporter-path "$THIS_DIR/packager-reporter.js" "$@"`. Can we call this directly instead? It seems to be doing the right thing when I call it manually.

Comment (szymonrybczak) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: Yes, but there are limitation with `open` command, if we're running `run-ios` or `run-android` a new terminal window is opened and that's why I created `launchPackeger.command` & `.packager.env` inside CLI, because we can't unfortunately pass command with arguments to new created window.  See here: https://github.com/react-native-community/cli/pull/1812#discussion_r1092434402 But with these files I can store information in `.packager.env` and launch packager in new terminal window with `launchPackager.command`.

Comment (tido64) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: Can we pass `--args` and/or `--env` options to `open`?
image

Comment (tido64) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: Sorry, I had assumed that when it says `launchPackager.command` here, that you're referring to `react-native/scripts/launchPackager.command`. I missed that you had created your own. 🤦‍♂️

This is looks fine. The only objection is trying to resolve `@react-native-community/cli-plugin-metro` from this package. As mentioned earlier, this assumes hoisting and you might pick up the wrong version. For this to work correctly, I think we have to do one of two things:

1. Add `@react-native-community/cli-plugin-metro` as a dependency of `@react-native-community/cli-platform-android`. This will ensure that `cli-platform-android` gets the correct copy linked into its `node_modules` folder if necessary.
2. Resolve `@react-native-community/cli-plugin-metro` via `@react-native-community/cli`. This is a bit more frail since it assumes that `cli-platform-android` was installed via `cli`, which may be okay here.

Comment (szymonrybczak) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: I think the first solution you proposed is better. 👍

Comment (szymonrybczak) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: But there's a problem when we add `@react-native-community/cli-plugin-metro` to `package.json`, and we try to find this package via `require.resolve('@react-native-community/cli-plugin-metro/package.json')` it finds this package inside `node_modules` but in CLI (`/Users/szymonrybczak/callstack/forked-cli/packages/cli-platform-android/node_modules/@react-native-community/cli-plugin-metro/build/launchPackager.command`).

File: packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts [hunk 4]
```diff
@@ -17,19 +21,16 @@ export function startServerInNewWindow(
...
-  const launchPackagerScript = path.join(
-    reactNativePath,
-    `scripts/${scriptFile}`,
-  );
+  const launchPackagerScript = path.join(reactNativeCliPath, `${scriptFile}`);
 
   /**
-   * Set up the `launchpackager.(command|bat)` file.
+   * Set up the `launchPackager.(command|bat)` file.
    * It lives next to `.packager.(bat|env)`
```
[the remark this answers is not in the document]
Comment (szymonrybczak) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:34]: Yeah, I'm also not fan of this. That's good idea but on the other hand the problem is `.packager.env` file right now lives next to `launchPackager.sh` so we're 100% sure about file path and we can make `source "$THIS_DIR/.packager.env"`. But when we move `.packager.env` to e.g. `packages/app-one/node_modules/.packager.env` and we try to run the script which is e.g. in `node_modules/react-native-community/cli-plugin-metro/launchPackager.sh` we can't source the `.packager.env` file because we don't its path. 😟

File: packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts (hunk 3 above)
Comment (tido64) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:11]: Oh, does the version number match what is used in `@react-native-community/cli`? If the two match, they should be deduped. I don't think you should see a separate copy there.

File: packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (tido64) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:34]: Oof, yeah… Can we generate `node_modules/.bin/launchPackager.sh` instead and pass that script to `open`? That way we will always know where the project root is.

**Comment by szymonrybczak** [comment]
Hey @tido64, I updated my code. Could you please take a look at it again? 🙏

File: packages/cli-plugin-metro/launchPackager.command [hunk 5]
```diff
@@ -0,0 +1,8 @@
+THIS_DIR=$(cd -P "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)
+
+. $THIS_DIR/launchPackager.sh
```
Comment (tido64) [inline packages/cli-plugin-metro/launchPackager.command:3]: Is there a reason for why we need to call `launchPackager.sh`? Can we merge these files?

File: .gitignore [hunk 6]
```diff
@@ -12,3 +12,4 @@ build/
 .watchmanconfig
 coverage
 !packages/cli-platform-ios/src/config/__fixtures__/native_modules/node_modules
+*.env
```
Comment (tido64) [inline .gitignore:15]: Nit: If you add a newline here, you won't get this "invalid" mark:
image

File: packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts [hunk 7]
```diff
@@ -16,34 +17,50 @@ export function startServerInNewWindow(
     ? 'launchPackager.bat'
     : 'launchPackager.command';
   const packagerEnvFilename = isWindows ? '.packager.bat' : '.packager.env';
-  const portExportContent = isWindows
-    ? `set RCT_METRO_PORT=${port}`
-    : `export RCT_METRO_PORT=${port}`;
+  const packagerEnvFileExportContent = isWindows
+    ? `set RCT_METRO_PORT=${port}\nset PROJECT_ROOT=${projectRoot}\nset REACT_NATIVE_PATH=${reactNativePath}`
+    : `export RCT_METRO_PORT=${port}\nexport PROJECT_ROOT=${projectRoot}\nexport REACT_NATIVE_PATH=${reactNativePath}`;
+  const nodeModulesPath = path.join(projectRoot, 'node_modules/.bin');
```
Comment (tido64) [inline packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:23]: Nit: Use `path.join` to join the last part as well?
```suggestion
  const nodeModulesPath = path.join(projectRoot, 'node_modules', '.bin');
```

**Review by tido64 — APPROVED** [review]
Looks good to me! Thanks for fixing this, @szymonrybczak ❤️

File: packages/cli-plugin-metro/launchPackager.command (hunk 5 above)
Comment (szymonrybczak) [reply packages/cli-plugin-metro/launchPackager.command]: Yup, I checked it and if I change permission to `launchPackager.sh` the `launchPackager.command` file is useless.

**Review by kelset — APPROVED** [review]
:shipit:

File: packages/cli-plugin-metro/launchPackager.sh [hunk 8]
```diff
@@ -0,0 +1,4 @@
+THIS_DIR=$(cd -P "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)
+source "$THIS_DIR/.packager.env"
+cd $PROJECT_ROOT
+$REACT_NATIVE_PATH/cli.js start
```
Comment (tido64) [inline packages/cli-plugin-metro/launchPackager.sh:4]: Should we carry over this block from `launchPackager.command`?
```sh
if [[ -z "$CI" ]]; then
  echo "Process terminated. Press <enter> to close the window"
  read -r
fi
```

Comment (szymonrybczak) [reply packages/cli-plugin-metro/launchPackager.sh:4]: Yes, we should.

File: packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts [hunk 9]
```diff
@@ -6,44 +6,55 @@ import {logger} from '@react-native-community/cli-tools';
...
+   * Copy files into `node_modules/.bin`.
+   */
+  fs.copyFileSync(
+    path.join(cliPluginMetroPath, 'launchPackager.bat'),
+    path.join(nodeModulesPath, 'launchPackager.bat'),
+  );
+  fs.copyFileSync(
+    path.join(cliPluginMetroPath, 'launchPackager.sh'),
+    path.join(nodeModulesPath, 'launchPackager.sh'),
+  );
```
Comment (thymikee) [inline packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:56]: let's add some exception handling here, letting users know what happened and what they can do (e.g. retry)

Comment (szymonrybczak) [reply packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts:56]: done! ✅
